"""ATT JWT IN TB_USERS

Revision ID: 330c6c27fc3c
Revises: 
Create Date: 2025-08-09 17:54:10.935084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '330c6c27fc3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jwt', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('jwt_iat', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['jwt'])
        batch_op.create_unique_constraint(None, ['jwt_iat'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('jwt_iat')
        batch_op.drop_column('jwt')

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_column('preco')

    # ### end Alembic commands ###
