"""initial

Revision ID: 4a9d8fb3a470
Revises: 
Create Date: 2025-08-11 00:13:28.615805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a9d8fb3a470'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfil',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=15), nullable=False),
    sa.Column('sobrenome', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tell', sa.VARCHAR(length=20), nullable=True),
    sa.Column('setor', sa.VARCHAR(length=20), nullable=True),
    sa.Column('cargo', sa.VARCHAR(length=30), nullable=False),
    sa.Column('cnh', sa.VARCHAR(length=13), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnh')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('pwd', sa.VARCHAR(length=188), nullable=True),
    sa.Column('falg_alter_pwd', sa.Boolean(), nullable=True),
    sa.Column('flag_confirm_email', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('jwt', sa.String(length=500), nullable=True),
    sa.Column('jwt_iat', sa.String(length=50), nullable=True),
    sa.Column('token', sa.String(length=8), nullable=False),
    sa.Column('autor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('jwt'),
    sa.UniqueConstraint('jwt_iat'),
    sa.UniqueConstraint('token')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_cliente', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('endereco', sa.String(length=200), nullable=False),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_cliente')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_pedido', sa.String(length=10), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('data_pedido', sa.DateTime(), nullable=True),
    sa.Column('nome_arquivo_original', sa.String(length=255), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_pedido')
    )
    op.create_table('pedido_produto',
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('pedido_id', 'produto_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedido_produto')
    op.drop_table('pedidos')
    op.drop_table('clientes')
    op.drop_table('users')
    op.drop_table('produtos')
    op.drop_table('perfil')
    # ### end Alembic commands ###
